### ISSUE TITLE
Ломается сборка css переменных --shadow

### ISSUE THREAD

**Issue by PutilovAI** [alfa-laboratory/arui-scripts#113]
Коряво компилирует переменные
```
// node_modules/arui-feather/vars/shadow.css
--shadow-light-color: color(var(--shadow-color) a(.25));
--shadow-light: 0 1px 5px 0 var(--shadow-light-color);
// chat-main.css
box-shadow: var(--shadow-light);
// на выходе
box-shadow: 01 px5px0color(#0b1f35 a(.25));
```

Ломаться начинает с версии 8.5.1. Когда затащили в проект кастомную либу для css переменных
`"@alfalab/postcss-custom-properties": "^9.1.1",`
вместо
`"postcss-custom-properties": "^7.0.0",`

Вот ПР https://github.com/alfa-laboratory/arui-scripts/commit/1c8029b76133776cfb2094afa83680ba20671c7b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by reme3d2y** [comment]
https://github.com/postcss/postcss-custom-properties/issues/218

Попробую исправить у нас в форке и открою им PR
