### ISSUE TITLE
Не работает динамический импорт в node_modules 

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/arui-scripts#142]
## Проблема
Если какой-то модуль из `node_modules` использует внутри себя динамический импорт, то модуль, который импортируется динамически, попадает в бандл `vendors.js`, а не в отдельный чанк.

## Пример
Есть компонент в фижере [IntlPhoneInput](https://digital.alfabank.ru/components/intlphoneinput).
Он внутри себя делает динамический импорт библиотеки `libphonenumber-js`.
В результате она попадает в `vendors.js`, а должна подгружаться динамически на страницу отдельным чанком

**Comment by Heymdall** [comment]
Фикс попал в версию 9.7.0
