### ISSUE TITLE
Удалить /var/lib из dockerfile в версиях ниже 9.7.0 включительно

### ISSUE THREAD

**Issue by IskanderIV** [alfa-laboratory/arui-scripts#153]
Есть подозрение, что строчка 5 chown -R nginx:nginx /var/lib/nginx && \\ в arui-scripts/templates/dockerfile.template.js валит сборку образа, если runFromNonRootUser == true
При поднятии базового образа в нем отсутствует директория /var/lib

**Comment by sklyanchuk** [comment]
Заработало с проставлением докер образа `baseDockerImage”: “heymdall/alpine-node-nginx:12.16.1`

**Comment by IskanderIV** [comment]
Принял. Закрываю
