### ISSUE TITLE
Как сказать серверному приложению где лежат файлы клиентского приложения?

### ISSUE THREAD

**Issue by krutoo** [alfa-laboratory/arui-scripts#162]
Привет, есть следующая задача:

Необходимо написать node-приложение для вывода html-страницы с SSR.

Приложение должно отдавать ответ в формате HTML c начальной версткой в которой есть скрипты и стили, собираемые посредством клиентской точки входа (`src/clinet/index.js`)

Возможно ли как-то сообщить серверному приложению откуда брать ссылки на скрипты и стили чтобы далее вставить их в начальную разметку (например через зашивание переменной среды) ?

**Comment by Heymdall** [comment]
После сборки клиентского приложения формируется файл `.build/webpack-assets.json`, содержащий правильные ссылки на ассеты. Их можно использовать на серверной стороне. Это описано в [документации](https://github.com/alfa-laboratory/arui-scripts/tree/master/packages/arui-scripts#пути-до-ассетов)
