### ISSUE TITLE
source-map in production

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-scripts#43]
https://github.com/alfa-laboratory/arui-scripts/blob/master/configs/webpack.server.prod.js#L160

давайте обсудим вот это. Из-за этого нужно ставить source-map-support хотя по факту , на проде вроде это не надо, давайте обсуждать что с этим делать

**Comment by 7rulnik** [comment]
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2019-10-11-version-12120-current-bridgear нода вроде уже поддерживает сорсмапы нативно

**Comment by stepancar** [comment]
@Heymdall @Luchanso @samoxbal @ilatovsky

**Comment by Heymdall** [comment]
Ну нода поддерживает, но за флагом.
А в чем проблема с этой штукой? в целом мне кажется что в стак трейсах приятнее видеть все же исходники, а не скомпиленый код. И несколько раз мы таки ловили ошибки нодовые на проде. 
Если реально мешает - можно в try catch завернуть

**Comment by stepancar** [comment]
@Heymdall проблема только в том, что в проекте есть зависимость, которая нигде не используется и валится все в рантайме и то только если prune делать. Поэтому ее есть шанс всегда нечаянно снести.

**Comment by stepancar** [comment]
Вон соседний issue https://github.com/alfa-laboratory/arui-scripts/issues/15

**Comment by Luchanso** [comment]
Может вынесем эту зависимость прямо явно в arui-scripts?

**Comment by stepancar** [comment]
@Luchanso при сборке докера или тара скрипты делают prune в конце. Это значит что зависимость, которую принисла dev зависимость - будет удалена

**Comment by samoxbal** [comment]
Я предлагаю убрать ее из скриптов и ставить явно в проекте если нужна. Сейчас у нас наблюдаются проблемы при раскатке, когда делается prune - при построении списка зависимостей очищается все, что ниже source-map-support в дереве.
