### ISSUE TITLE
Хотелось бы иметь возможность указать тут https

### ISSUE THREAD

**Issue by ariran-5** [alfa-laboratory/arui-scripts#51]
https://github.com/alfa-laboratory/arui-scripts/blob/b2a8e16557a914e629b463d5f56440e33d8d974c/configs/dev-server.js#L15

**Comment by Heymdall** [comment]
Для dev режима? А какой вообще юз-кейс для этого? Просто на мой взгляд сама по себе нода вообще про https не особо знать должна

**Comment by ariran-5** [comment]
Ложная тревога, в тонкой настройке обошлось

**Comment by ariran-5** [comment]
Если ноду поднимать на http2 для пушей то знать о https ей приходится )

**Comment by ariran-5** [comment]
Нашел в доках о моем случае 
https://webpack.js.org/configuration/dev-server/#devserverhttp2
