### ISSUE TITLE
arui-scripts/ aruiScripts

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-scripts#56]
Хочу выпилить лишние настройки. Сейчас все проекты на aruiScripts но скрипты поддерживают arui-scripts. Зачем?

**Comment by Heymdall** [comment]
Не все. У корпов точно есть пяток с `arui-scripts`. Можно выпилить и как мажорку выпустить, но я не уверен в необходимости такого. Кода для поддержки обоих вариантов не очень много

**Comment by stepancar** [comment]
Давай выберем предпочтительный способ. Дело в том что когда ты захочешь понять используется ли та или иная опция - ты пойдешь по репам и будешь анализировать что в package.json и тебе будет сложнее поддержать 2 варианта. Давай в этой итерации запилим warning?

**Comment by Heymdall** [comment]
давай выпилим. И ошибку кидать будем с описанием что надо делать. Ну и мажорка.
