### ISSUE TITLE
может добавим tsconfig-paths-webpack-plugin ?

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-scripts#60]
https://www.npmjs.com/package/tsconfig-paths-webpack-plugin

**Comment by stepancar** [comment]
@ilatovsky подкинул идею юзать такой плагин. Вроде ниче не сломаем.

@Heymdall @Luchanso @aweppc @etroynov че скажете?

**Comment by Luchanso** [comment]
С этими ~костылями~ относительными путями больше проблем, чем пользы, но давайте попробуем 👍
