### ISSUE TITLE
getLocalIdentPattern для микросервисов с хост приложением

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-scripts#81]
У нас есть layout ui который сквозной для всех проектов. У нас есть не переиспользуемый но похожий код в двух приложениях;

Получили перетирающие классы в css модулях, карл. 
Паттерн который генерит имя выглядит так
```return '[name]__[local]__[hash:base64:5]';```

Че будем делать?
@etroynov кинь примеры

**Comment by 7rulnik** [comment]
Круто. `'[path][name]__[local]--[hash:base64:5]'` — это не поможет?

**Comment by stepancar** [comment]
https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/getCSSModuleLocalIdent.js
давайте везьмем то что чуваки используют

**Comment by stepancar** [comment]
@7rulnik у вас такая?

**Comment by 7rulnik** [comment]
@stepancar не, у нас `localIdentName: ifDev('[local]__[hash:base64:5]', '[hash:base64:8]')`

**Comment by etroynov** [comment]
Одобряю подход реукта!

**Comment by stepancar** [comment]
@etroynov так с тем как ты предлагаешь именовать файлы это не будет работать
https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/getCSSModuleLocalIdent.js#L21

Ты же называешь файл Component.module.css

**Comment by etroynov** [comment]
похоже да я предполагал что он рандомный хэш генерит но похоже это не так, тут либо брать имя папки за основу для класса, либо именовать файлы именем компонента.  Печаль :(

**Comment by stepancar** [comment]
@etroynov так если файл называть index.module.css - все будет работать. Дай посмотреть на то гле ты взял вот этот прикол с таким неймингом. не нашел такой практики

**Comment by Heymdall** [comment]
А кто вообще знает от чего именно хэш генерится? Потому что кажется что заменяя имя файла на название папки мы просто шило на мыло меняем. И просто при другом подходе к неймингу это может так же выстрелить. Пихать в название сразу имя папки и имя файла не хочется, слишком длинно получается, но как то хочется это порешать более универсально

**Comment by Heymdall** [comment]
И можно хоть какой то тест-кейс привести с такой коллизией? В тесты его например добавить...

**Comment by stepancar** [comment]
@Heymdall , я в итоге заливаю https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/getCSSModuleLocalIdent.js#L21
Потому что это стандарт. Именовать будем как все. Проблемы с наложением стилей будем рассматривать и решть без аффекта на остальных
