### ISSUE TITLE
Could not find plugin "proposal-numeric-separator"

### ISSUE THREAD

**Issue by Nadezzdi** [alfa-laboratory/arui-scripts#95]
Не собирается проект на версиях arui-scripts выше 8.2.3, сборка падает с ошибкой
[Client] Error: [BABEL] /Users/nadine/alfa-projects/ufr-uzp-mainpage-ui/src/index.tsx: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/nadine/alfa-projects/ufr-uzp-mainpage-ui/node_modules/arui-scripts/node_modules/@babel/preset-env/lib/index.js")

Проблема в версии @babel/presets-env в зависимостях Пишут, что сломаны версии 7.8.0-7.8.6
[https://github.com/facebook/create-react-app/issues/8680#issuecomment-601851525](url)

**Comment by Luchanso** [comment]
Fixed in #96
